# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        reduc:
            quality: 75
            filters:
                thumbnail:
                    size: [350, 200]
                    mode: outbound
        portfolio:
            quality: 100
            filters:
                thumbnail:
                    size: [ 490, 320 ]
                    mode: outbound
        show:
            quality: 100
            filters:
                thumbnail:
                    size: [ 532, 338 ]
                    mode: outbound
        mobil:
            quality: 100
            filters:
                thumbnail:
                    size: [ 232, 367 ]
                    mode: outbound
