vich_uploader:
    db_driver: orm

    mappings:
        portfolio:
            uri_prefix: /image/uploads
            upload_destination: '%kernel.project_dir%/public/image/uploads'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
